#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/web/wp/wp-load.php';

use Brocooly\Commands;
use Symfony\Component\Console\Application;

if ( isProduction() ) {
	echo 'Not allowed in production';
	exit;
}

$app = new Application();

# add your commands
$commands = Commands::get();

foreach ( $commands as $command ) {
	$app->add( new $command() );
}

$app->run();
