<?php
/**
 * ! Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 *
 * @package Brocooly
 */

/**
 * --------------------------------------------------------------------------
 * Include vendor files
 * --------------------------------------------------------------------------
 */
require_once dirname( __DIR__ ) . '/vendor/autoload.php';

/**
 * --------------------------------------------------------------------------
 * Include app environment configuration
 * --------------------------------------------------------------------------
 *
 * This file will define which environment parameters to load
 */
require_once dirname( __DIR__ ) . '/config/app.php';

/**
 * --------------------------------------------------------------------------
 * Boot WordPress
 * --------------------------------------------------------------------------
 */
require_once ABSPATH . 'wp-settings.php';
